"""empty message

Revision ID: 50c4af9bf49e
Revises: 53b19a825e27
Create Date: 2022-11-18 15:57:00.256071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50c4af9bf49e'
down_revision = '53b19a825e27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
